### ISSUE TITLE
eks-argocd-terraform-infra/tree/main/modules/s3-backend issue in this part

### ISSUE THREAD

**Issue by beta-teaser** [DevOps-Engineers-Team/eks-argocd-terraform-infra#1]
https://github.com/DevOps-Engineers-Team/eks-argocd-terraform-infra/tree/main/modules/s3-backend

terraform apply don't work here. Missing region declaration and missing bucket access policy roles

**Comment by WitoldSlawko** [comment]
hi , 

1. bucket policy is set here https://github.com/DevOps-Engineers-Team/eks-argocd-terraform-infra/blob/main/modules/s3-backend/main.tf#L30 , and IAM roles to those are passed here https://github.com/DevOps-Engineers-Team/eks-argocd-terraform-infra/blob/main/modules/s3-backend/main.tf#L80

2. for the region, it only needs to be setup here, either on:
- provider level: https://github.com/DevOps-Engineers-Team/eks-argocd-terraform-infra/blob/main/core-infra/develop/s3-backend/provider.tf#L2
- if you wish to use OIDC role via github action workflow then also here: https://github.com/DevOps-Engineers-Team/eks-argocd-terraform-infra/blob/main/.github/workflows/later-terraform-apply.yml#LL38C3-L38C3 

edit: also created and merged PR as backend s3 configs were missing

hence, I am closing the issue  :)
